import { Item } from "../types";

export const initialItems: Item[] = [
  {
    id: "1",
    name: "Vintage Camera",
    category: "Electronics",
    description: "A beautifully restored vintage 35mm film camera with a leather strap. Perfect for street photography and classic aesthetics.",
    tags: ["Vintage", "Photography", "Retro"],
    value: 299.99,
    rating: 4.8,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/vintage-camera-ec93c455-1783005073847.webp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Wireless Headphones",
    category: "Electronics",
    description: "Sleek, modern wireless headphones with active noise cancellation and 40 hours of battery life.",
    tags: ["Audio", "Tech", "Minimalist"],
    value: 199.50,
    rating: 4.5,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/wireless-headphones-13a9bde0-1783005076690.webp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Organic Coffee Beans",
    category: "Lifestyle",
    description: "Ethically sourced, single-origin coffee beans roasted to perfection. Notes of chocolate and berry.",
    tags: ["Food", "Organic", "Premium"],
    value: 24.00,
    rating: 4.9,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/organic-coffee-beans-335a1ee2-1783005076718.webp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Classic Novel Collection",
    category: "Reading",
    description: "A leather-bound collection of timeless classics. Essential for any home library.",
    tags: ["Books", "Education", "Decor"],
    value: 85.00,
    rating: 4.7,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/classic-novel-003a8349-1783005074910.webp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Modern Smartwatch",
    category: "Electronics",
    description: "Advanced health tracking and notification features in a lightweight titanium body.",
    tags: ["Fitness", "Wearable", "Tech"],
    value: 349.00,
    rating: 4.6,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/modern-smartwatch-a696f65a-1783005075495.webp",
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Succulent Plant Set",
    category: "Home",
    description: "A variety of low-maintenance succulent plants in handcrafted geometric ceramic pots.",
    tags: ["Garden", "Home Decor", "Greenery"],
    value: 45.00,
    rating: 4.4,
    image: "https://storage.googleapis.com/dala-prod-public-storage/generated-images/ca465ded-9418-41e8-8402-15c7b6ed8a20/succulent-plant-b1b78a0f-1783005075331.webp",
    createdAt: new Date().toISOString(),
  }
];
